RoughCaveB1_MapScripts::
	.byte 0


RoughCaveB1_Hiker::
# 6 "data/maps/RoughCaveB1/scripts.pory"
	lock
# 7 "data/maps/RoughCaveB1/scripts.pory"
	faceplayer
# 8 "data/maps/RoughCaveB1/scripts.pory"
	msgbox RoughCaveHikerText
# 9 "data/maps/RoughCaveB1/scripts.pory"
	release
	end


RoughCaveHikerText::
# 13 "data/maps/RoughCaveB1/scripts.pory"
	.string "There's a chilling breeze in here, but I\n"
	.string "can't figure out where it's coming from…\p"
	.string "Perhaps somewhere further in…$"
